export interface CountryOption {
  name: string;
  code: string;
}

export const COUNTRIES: CountryOption[] = [
  { name: 'United Arab Emirates', code: '+971' },
  { name: 'Oman', code: '+968' },
  { name: 'Saudi Arabia', code: '+966' },
  { name: 'Qatar', code: '+974' },
  { name: 'Bahrain', code: '+973' },
  { name: 'Kuwait', code: '+965' },
  { name: 'Jordan', code: '+962' },
  { name: 'Lebanon', code: '+961' },
  { name: 'Iraq', code: '+964' },
  { name: 'Egypt', code: '+20' },
  { name: 'India', code: '+91' },
  { name: 'Pakistan', code: '+92' },
  { name: 'Bangladesh', code: '+880' },
  { name: 'Sri Lanka', code: '+94' },
  { name: 'Nepal', code: '+977' },
  { name: 'Philippines', code: '+63' },
  { name: 'Indonesia', code: '+62' },
  { name: 'Malaysia', code: '+60' },
  { name: 'Singapore', code: '+65' },
  { name: 'China', code: '+86' },
  { name: 'Japan', code: '+81' },
  { name: 'South Korea', code: '+82' },
  { name: 'United Kingdom', code: '+44' },
  { name: 'United States', code: '+1' },
  { name: 'Canada', code: '+1' },
  { name: 'Germany', code: '+49' },
  { name: 'France', code: '+33' },
  { name: 'Italy', code: '+39' },
  { name: 'Spain', code: '+34' },
  { name: 'Netherlands', code: '+31' },
  { name: 'Switzerland', code: '+41' },
  { name: 'Australia', code: '+61' },
  { name: 'New Zealand', code: '+64' },
  { name: 'South Africa', code: '+27' },
  { name: 'Nigeria', code: '+234' },
  { name: 'Kenya', code: '+254' },
  { name: 'Turkey', code: '+90' },
  { name: 'Russia', code: '+7' },
  { name: 'Brazil', code: '+55' },
  { name: 'Mexico', code: '+52' },
];

export const TIME_ZONES: string[] = [
  'GMT-12:00 (Baker Island)',
  'GMT-08:00 (Los Angeles)',
  'GMT-07:00 (Denver)',
  'GMT-06:00 (Chicago)',
  'GMT-05:00 (New York)',
  'GMT-04:00 (Halifax)',
  'GMT-03:00 (Sao Paulo)',
  'GMT+00:00 (UTC / London)',
  'GMT+01:00 (Berlin)',
  'GMT+02:00 (Cairo)',
  'GMT+03:00 (Moscow)',
  'GMT+03:30 (Tehran)',
  'GMT+04:00 (Dubai)',
  'GMT+04:30 (Kabul)',
  'GMT+05:00 (Karachi)',
  'GMT+05:30 (India)',
  'GMT+06:00 (Dhaka)',
  'GMT+07:00 (Bangkok)',
  'GMT+08:00 (Singapore)',
  'GMT+09:00 (Tokyo)',
  'GMT+10:00 (Sydney)',
  'GMT+12:00 (Auckland)',
];
